### ISSUE TITLE
CC Primary editor when a pitch is approved

### ISSUE THREAD

**Issue by amit-sawhney** [hack4impact-uiuc/south-side-weekly#159]
## Description

When a pitch is approved, the primary editor should be cc'ed in the email notification that is sent to the writer. (A separate notification email for primary editor is unnecessary, but no worries if preventing that will take a decent amount of time to implement.) There should be a line within the email that mentions that the primary editor has been cc'ed and that they will be working together on the story.

Note: Some times the writer is specified when a pitch is approved. Other times, the writer is specified later on (they can either be added to the story or their claim request could be approved). All of these cases are relevant.

## Learning objectives

- Nodemailer

## Todo

- Revise email templates
- cc the primary editor in notification emails (see which email templates are relevant below)

## Useful links

- [Email templates](https://docs.google.com/document/d/1pLJHi1S6ZgaVt6dp3ooR1YqycSPlsLdz7kHW3Ysw88A/edit) (see the following templates: Pitch Approved (wants to write), Story Claim Request Approved, Staff Added Contributor to Story)

**Comment by chenfeiyu132** [comment]
Resolved by #170
