### ISSUE TITLE
Migrate to Table to design for pitch doc

### ISSUE THREAD

**Issue by amit-sawhney** [hack4impact-uiuc/south-side-weekly#163]
## Description

Convert the card view to a table view on the pitchdoc

![image](https://user-images.githubusercontent.com/66758185/138996393-739d8a28-5c95-43fd-a225-d547b73e6783.png)

## Todo

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- Generalize Directory component
- Change pitch doc to table

**Comment by sahithimuthyala** [comment]
@ayanmallik We can close this issue, right?

**Comment by ayanmallik** [comment]
> @ayanmallik We can close this issue, right?
Yes, closing issue
